<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.DailyConsolidation.Application\CashFlow.DailyConsolidation.Application.csproj" />
    <ProjectReference Include="..\CashFlow.DailyConsolidation.Infrastructure\CashFlow.DailyConsolidation.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
